url: "https://n4brain.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/spintrack" # the subpath of your site, e.g. /blog
title: "SPIN track" # the name of your site, e.g. ACME Corp.
include:
- software
- forge
- repo
defaults:
  - 
    scope:
      path: "index.md" # an empty string here means all files in the project
    values:
      layout: "default"
  - 
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "project"
